name: Update Helm Charts
on:
  push:
    branches: [ main ]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Package Charts
        run: |
          for chart in */; do
            helm package "$chart" -d ./
          done
          helm repo index . --url https://2Sage.github.io/helm-charts
      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update charts"
          git push